landing_app/urls.py
from django.urls import path
from .views import *




app_name = 'landing'

urlpatterns = [
    path('', home_view, name="home"),
    path('about/', about_view, name="about"),
    path('contact/', contact_view, name="contact"),
    path('pharmacy/', pharmacy_view, name="pharmacy"),
    path('product/', product_view, name="product"),
    path('product/<slug:slug>/', product_detail_view, name="product_detail"),
    path('service/', service_view, name="service"),
    path('service/<slug:slug>/', service_detail_view, name="service_detail"),
    path('blog/', blog_view, name="blog"),
    path('blog/<slug:slug>/', blog_detail_view, name="blog_detail"),
    
    # Dashboard Pharmacist
    path('pharmacist-dashboard/', pharmacist_dashboard_view, name="pharmacist_dashboard"),
    path('pharmacist-add-profile/', phcist_add_profile_view, name="phcist_add_profile"),
    path('appointment/', appointment_view, name="appointment"),

    path('pharmacist-patient/', phcist_patient_view, name="phcist_patient"),
    path('pharmacist-patient-profile/', phcist_patient_profile_view, name="phcist_patient_profile"),
    path('add-prescription/', add_prescription_view, name="add_prescription"),
    path('add-billing/', add_billing_view, name="add_billing"),
    path('pharmacist-invoice/', phcist_invoice_view, name="phcist_invoice"),
    path('pharmacist-show-invoice/', phcist_show_invoice_view, name="phcist_show_invoice"),
    path('pharmacist-register/', phcist_register_view, name="phcist_register"),
    path('pharmacist-login/', phcist_login_view, name="phcist_login"),
    path('pharmacist-add-blog/', phcist_add_blog_view, name="phcist_add_blog"),
    
    # Dashboard Client
    path('patient-dashboard/', patient_dashboard_view, name="patient_dashboard"),
    path('search-pharmacist/', search_pharmacist_view, name="search_pharmacist"),
    path('pharmacist-profile/', phcist_profile_view, name="pharmacist_profile"),
    path('patient-checkout/', checkout_view, name="patient_checkout"),
    path('patient-booking/', booking_view, name="patient_booking"),
    path('favorite-pharmacist/', favorite_pharmacist_view, name="favorite_pharmacist"),
    path('patient-add-profile/', patient_add_profile_view, name="patient_add_profile"),
    path('patient-change-password/', patient_change_password_view, name="patient_change_password"),
    
    
    # Admin Pharmacy
    path('admin-pharmacy/', pharmacy_admin_view, name="pharmacy_admin"),
]

pharmacy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from dashboard_app.views import PasswordChangeView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/password/change/', PasswordChangeView.as_view(), name="account_change_password"),
    path('accounts/', include('allauth.urls')),
    path('', include('landing_app.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('dashboard/', include('dashboard_app.urls')),
    path('patient/', include('patient_app.urls')),
    # path('search/', include('search.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



#Modify Site Header
admin.site.site_header = 'Pharmacie Administration'
#Modify Site Title
admin.site.site_title = 'Pharmacie'
#Modify Site Index Title
admin.site.index_title = 'Pharmacie Administration'
#Modify Site URL

templates/landing/service/detail.html
{% extends "landing/base.html" %}
{% load static %}
{% block title %}Detail Déploiement{% endblock %}


{% block content %}
    <div class="main-wrapper">

        <div class="breadcrumb-bar-six">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-md-12 col-12">
                        <h2 class="breadcrumb-title">Déploiement</h2>
                        <nav aria-label="breadcrumb" class="page-breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item">
                                    <a href="/">Accueil</a>
                                </li>
                                <li class="breadcrumb-item">
                                    <a href="{% url 'landing:service' %}">Déploiement</a>
                                </li>
                                <li class="breadcrumb-item active" aria-current="page">Détails</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
        <div class="content pharmacy-cart-content">
            <div class="container">
                {% include 'message.html' %}
                <div class="card pharmacy-card">
                    <div class="card-body">
                        <div class="doctor-widget pharmacy-widget">
                            <div class="doc-info-left">
                                <div class="doctor-img1">
                                    <a href="javascript:void(0)">
                                        {% if service.photo %}
                                        <img src="{{ service.photo.url }}" class="img-fluid"
                                            alt="{{ service.name|title }}"  style="width: 100%; height: 230px; object-fit: cover;">
                                        {% else %}
                                            <img src="{% static 'assets/img/ban-bg-01.png' %}" class="img-fluid"
                                        alt="{{ service.name|title }}"  style="width: 100%; height: 230px; object-fit: cover;">
                                        {% endif %}
                                    </a>
                                </div>
                                <div class="doc-info-cont">
                                    <h4 class="doc-name">
                                        <a href="javascript:void(0)">{{ service.name|title }}</a>
                                    </h4>
                                    <div class="clinic-details">
                                        <div class="clini-infos">
                                            <p class="doc-location">
                                                <i class="feather-feather"></i> {{ service.category }}
                                            </p>
                                        </div>
                                    </div>
                                    <!-- <div class="pharmacy-social-links">
                                        <ul class="nav">
                                            <li>
                                                <a href="https://www.facebook.com/" target="_blank">
                                                    <i class="fab fa-facebook"></i>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="https://twitter.com/" target="_blank">
                                                    <i class="fab fa-twitter"></i>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="https://www.instagram.com/" target="_blank">
                                                    <i class="fab fa-instagram"></i>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="https://www.linkedin.com/" target="_blank">
                                                    <i class="fab fa-linkedin"></i>
                                                </a>
                                            </li>
                                        </ul>
                                    </div> -->
                                </div>
                            </div>
                            <div class="doc-info-right d-flex align-items-center justify-content-center">
                                <div class="pharmacy-booking pharmacy-booking-right">

                                    <a class="btn browse-products-btn" href="javascript:void(0)" data-bs-toggle="modal"
                                        data-bs-target="#voice_call">
                                        <i class="feather-phone-call"></i> Appelle maintenant </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="pharmacy-details-info">
                    <div class="tab-content pt-0">
                        <div role="tabpanel" id="about_store" class="tab-pane fade show active">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="widget about-widget">
                                        <p>{{ service.description|safe}}</p>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <section class="section section-feature">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="section-header sec-head text-center aos" data-aos="fade-up">
                            <h2>Déploiements reliés</h2>
                            <div class="owl-nav slide-nav-10 nav-control"></div>
                        </div>
                        <div class="brand-sliders owl-carousel owl-theme">
                            {% for product_related in services %}
                                <div class="features-brand aos" data-aos="fade-up">
                                    <div class="features-brand-img">
                                        {% if product_related.photo %}
                                            <a href="{{ product_related.landing_get_detail_url }}">
                                                <img src="{{ product_related.photo.url }}" style="width: 400px; height: 300px; object-fit: contain;" alt="{{ product_related.name|title }}" class="img-fluid">
                                            </a>
                                        {% else %}
                                            <a href="{{ product_related.landing_get_detail_url }}">
                                                <img src="{% static 'assets/img/ban-bg-01.png' %}" style="width: 100%; height: 230px; object-fit: cover;" alt="{{ product_related.name|title }}" class="img-fluid">
                                            </a>
                                        {% endif %}
                                    </div>
                                    <div class="feature-brand-overlay">
                                        <div class="feature-brand">
                                            <h4>
                                                <a href="{{ product_related.landing_get_detail_url }}">{{ product_related.name|title }}</a>
                                            </h4>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
{% endblock %}

templates/landing/service/index.html
{% extends "landing/base.html" %}
{% load static %}
{% block title %}Déploiement{% endblock %}


{% block content %}

<div class="main-wrapper">
    <div class="breadcrumb-bar-six">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-md-12 col-12">
                    <h2 class="breadcrumb-title">Déploiement</h2>
                    <nav aria-label="breadcrumb" class="page-breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="/">Accueil</a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">Déploiement</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <div class="content pharmacy-cart-content">
        <div class="container">
            {% include 'message.html' %}
            <div class="row">
                <div class="col-lg-3 col-xl-3 theiaStickySidebar">
                    <div class="filter-new">
                        <div class="filter-header">
                            <h4>Structures</h4>
                        </div>
                        <div class="filter-widget">
                            <ul>
                                <li>
                                    <a href="{% url 'landing:service' %}">Voir tout
                                    </a>
                                </li>
                                {% for category in categories %}
                                    <li>
                                        <a href="{% url 'landing:service' %}?category={{ category.slug }}">{{ category.name|title }} <span> ({{category.service_category.count}})</span>
                                        </a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-9 col-xl-9">
                    {% for service in services %}
                    <div class="card pharmacy-card">
                        <div class="card-body">
                            <div class="doctor-widget pharmacy-widget">
                                <div class="doc-info-left">
                                    <div class="doctor-img1">
                                        <a href="{{ service.get_detail_url }}">
                                            {% if service.photo %}
                                                <img src="{{ service.photo.url }}"  style="width: 400px; height: 300px; object-fit: cover;" class="img-fluid" alt="{{ service.name|title }}">
                                            {% else %}
                                                <img src="{% static 'assets/img/ban-bg-01.png' %}" style="width: 400px; height: 300px; object-fit: cover;" alt="{{ service.name|title }}" class="img-fluid">
                                            {% endif %}
                                        </a>
                                    </div>
                                    <div class="doc-info-cont">
                                        <h4 class="doc-name">
                                            <a href="{{ service.get_detail_url }}">{{ service.category }}</a>
                                        </h4>

                                        <div class="clinic-details">
                                            <div class="clini-infos">
                                                <p class="doc-location text-ellipse">
                                                    <i class="feather-tag"></i>Catégorie: {{ service.name|title }}
                                                </p>
                                                <p class="doc-location text-ellipse">
                                                    {{ service.description|safe|truncatechars:100 }}
                                                </p>
                                            </div>
                                        </div>
                                        <div class="pharmacy-booking">
                                            <a class="btn browse-products-btn" href="{{ service.get_detail_url }}">Voir les détails</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}

                    <!--Product Pagination -->

                    {% if services %}
                    {% include 'landing/service/pagination.html' %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>


    {% endblock %}

templates/landing/service/pagination.html
<!--Pagination-->
<div class="col-md-12 text-center">
    <div class="product-pagination">
        <nav>
            <ul class="pagination justify-content-end">
                <li class="page-item disabled">
                    <a class="page-link" href="javascript:void(0);" tabindex="-1">
                        <i class="fas fa-angle-left"></i>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="javascript:void(0);">1</a>
                </li>
                <li class="page-item active">
                    <a class="page-link" href="javascript:void(0);">2 <span class="visually-hidden">(current)</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="javascript:void(0);">3</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="javascript:void(0);">
                        <i class="fas fa-angle-right"></i>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</div>

<!--End Pagination-->